=== Rogedeen/arcane-folio/content/schemas/spell.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spell",
  "type": "object",
  "required": [
    "slug",
    "name",
    "level",
    "school",
    "castingTime",
    "range",
    "components",
    "duration",
    "description",
    "classes",
    "source",
    "source_ref",
    "license"
  ],
  "properties": {
    "slug": { "type": "string" },
    "name": { "type": "string" },
    "level": { "type": "integer", "minimum": 0, "maximum": 9 },
    "school": { "type": "string" },
    "castingTime": { "type": "string" },
    "range": { "type": "string" },
    "components": { "type": "string" },
    "duration": { "type": "string" },
    "description": { "type": "string" },
    "classes": {
      "type": "array",
      "items": { "type": "string" }
    },
    "source": { "type": "string" },
    "source_ref": { "type": "string" },
    "license": { "type": "string" }
  }
}

=== Rogedeen/arcane-folio/content/spells/1/bless.json
{
  "slug": "bless",
  "name": "Bless",
  "level": 1,
  "school": "Enchantment",
  "castingTime": "1 action",
  "range": "30 feet",
  "components": "V, S, M",
  "duration": "Concentration, up to 1 minute",
  "description": "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or saving throw, it can add a d4 to the result.",
  "classes": [
    "cleric",
    "paladin"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Bless",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/1/charm-person.json
{
  "slug": "charm-person",
  "name": "Charm Person",
  "level": 1,
  "school": "Enchantment",
  "castingTime": "1 action",
  "range": "30 feet",
  "components": "V, S",
  "duration": "1 hour",
  "description": "You attempt to charm a humanoid you can see within range. It must make a WIS save, and does so with advantage if you or your companions are fighting it.",
  "classes": [
    "bard",
    "druid",
    "sorcerer",
    "warlock",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Charm Person",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/0/thaumaturgy.json
{
  "slug": "thaumaturgy",
  "name": "Thaumaturgy",
  "level": 0,
  "school": "Transmutation",
  "castingTime": "1 action",
  "range": "30 feet",
  "components": "V",
  "duration": "Up to 1 minute",
  "description": "You manifest a minor wonder, a sign of supernatural power. Boom your voice, cause flames to flicker, or slam doors shut.",
  "classes": [
    "cleric"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Thaumaturgy",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/1/sleep.json
{
  "slug": "sleep",
  "name": "Sleep",
  "level": 1,
  "school": "Enchantment",
  "castingTime": "1 action",
  "range": "90 feet",
  "components": "V, S, M",
  "duration": "1 minute",
  "description": "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect.",
  "classes": [
    "bard",
    "sorcerer",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Sleep",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/2/suggestion.json
{
  "slug": "suggestion",
  "name": "Suggestion",
  "level": 2,
  "school": "Enchantment",
  "castingTime": "1 action",
  "range": "30 feet",
  "components": "V, M",
  "duration": "Concentration, up to 8 hours",
  "description": "You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range (WIS save negates).",
  "classes": [
    "bard",
    "sorcerer",
    "warlock",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Suggestion",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/0/guidance.json
{
  "slug": "guidance",
  "name": "Guidance",
  "level": 0,
  "school": "Divination",
  "castingTime": "1 action",
  "range": "Touch",
  "components": "V, S",
  "duration": "Concentration, up to 1 minute",
  "description": "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.",
  "classes": [
    "cleric",
    "druid"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Guidance",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/0/ray-of-frost.json
{
  "slug": "ray-of-frost",
  "name": "Ray of Frost",
  "level": 0,
  "school": "Evocation",
  "castingTime": "1 action",
  "range": "60 feet",
  "components": "V, S",
  "duration": "Instantaneous",
  "description": "A frigid beam of blue-white light streaks toward a creature within range. Ranged spell attack deals 1d8 cold damage and reduces speed by 10 ft.",
  "classes": [
    "sorcerer",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Ray of Frost",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/1/detect-magic.json
{
  "slug": "detect-magic",
  "name": "Detect Magic",
  "level": 1,
  "school": "Divination",
  "castingTime": "1 action (ritual)",
  "range": "Self",
  "components": "V, S",
  "duration": "Concentration, up to 10 minutes",
  "description": "For the duration, you sense the presence of magic within 30 feet of you and see a faint aura around any visible creature or object bearing magic.",
  "classes": [
    "bard",
    "cleric",
    "druid",
    "paladin",
    "ranger",
    "sorcerer",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Detect Magic",
  "license": "CC-BY-4.0"
}
