=== Rogedeen/arcane-folio/content/schemas/spell.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spell",
  "type": "object",
  "required": [
    "slug",
    "name",
    "level",
    "school",
    "castingTime",
    "range",
    "components",
    "duration",
    "description",
    "classes",
    "source",
    "source_ref",
    "license"
  ],
  "properties": {
    "slug": { "type": "string" },
    "name": { "type": "string" },
    "level": { "type": "integer", "minimum": 0, "maximum": 9 },
    "school": { "type": "string" },
    "castingTime": { "type": "string" },
    "range": { "type": "string" },
    "components": { "type": "string" },
    "duration": { "type": "string" },
    "description": { "type": "string" },
    "classes": {
      "type": "array",
      "items": { "type": "string" }
    },
    "source": { "type": "string" },
    "source_ref": { "type": "string" },
    "license": { "type": "string" }
  }
}

=== Rogedeen/arcane-folio/content/spells/1/cure-wounds.json
{
  "slug": "cure-wounds",
  "name": "Cure Wounds",
  "level": 1,
  "school": "Evocation",
  "castingTime": "1 action",
  "range": "Touch",
  "components": "V, S",
  "duration": "Instantaneous",
  "description": "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.",
  "classes": [
    "bard",
    "cleric",
    "druid",
    "paladin",
    "ranger"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Cure Wounds",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/3/haste.json
{
  "slug": "haste",
  "name": "Haste",
  "level": 3,
  "school": "Transmutation",
  "castingTime": "1 action",
  "range": "30 feet",
  "components": "V, S, M",
  "duration": "Concentration, up to 1 minute",
  "description": "Choose a willing creature that you can see within range. Its speed is doubled, it gains a +2 bonus to AC, it has advantage on DEX saves, and it gains an additional action.",
  "classes": [
    "sorcerer",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Haste",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/2/spiritual-weapon.json
{
  "slug": "spiritual-weapon",
  "name": "Spiritual Weapon",
  "level": 2,
  "school": "Evocation",
  "castingTime": "1 bonus action",
  "range": "60 feet",
  "components": "V, S",
  "duration": "1 minute",
  "description": "You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. Deals 1d8 + casting mod force damage.",
  "classes": [
    "cleric"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Spiritual Weapon",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/1/burning-hands.json
{
  "slug": "burning-hands",
  "name": "Burning Hands",
  "level": 1,
  "school": "Evocation",
  "castingTime": "1 action",
  "range": "Self (15-foot cone)",
  "components": "V, S",
  "duration": "Instantaneous",
  "description": "As you hold your hands with thumbs touching, a thin sheet of flames shoots forth. Each creature in a 15-foot cone takes 3d6 fire damage (DEX save half).",
  "classes": [
    "sorcerer",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Burning Hands",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/3/revivify.json
{
  "slug": "revivify",
  "name": "Revivify",
  "level": 3,
  "school": "Necromancy",
  "castingTime": "1 action",
  "range": "Touch",
  "components": "V, S, M",
  "duration": "Instantaneous",
  "description": "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.",
  "classes": [
    "cleric",
    "paladin"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Revivify",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/0/eldritch-blast.json
{
  "slug": "eldritch-blast",
  "name": "Eldritch Blast",
  "level": 0,
  "school": "Evocation",
  "castingTime": "1 action",
  "range": "120 feet",
  "components": "V, S",
  "duration": "Instantaneous",
  "description": "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack. On a hit, the target takes 1d10 force damage.",
  "classes": [
    "warlock"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Eldritch Blast",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/0/dancing-lights.json
{
  "slug": "dancing-lights",
  "name": "Dancing Lights",
  "level": 0,
  "school": "Evocation",
  "castingTime": "1 action",
  "range": "120 feet",
  "components": "V, S, M",
  "duration": "Concentration, up to 1 minute",
  "description": "You create up to four torch-sized lights within range, making them shed dim light in a 10-foot radius.",
  "classes": [
    "bard",
    "sorcerer",
    "wizard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Dancing Lights",
  "license": "CC-BY-4.0"
}

=== Rogedeen/arcane-folio/content/spells/0/vicious-mockery.json
{
  "slug": "vicious-mockery",
  "name": "Vicious Mockery",
  "level": 0,
  "school": "Enchantment",
  "castingTime": "1 action",
  "range": "60 feet",
  "components": "V",
  "duration": "Instantaneous",
  "description": "You unleash a string of insults laced with subtle enchantments. Target must succeed on a WIS save or take 1d4 psychic damage and disadvantage on next attack.",
  "classes": [
    "bard"
  ],
  "source": "SRD 5.1",
  "source_ref": "SRD 5.1, Spells: Vicious Mockery",
  "license": "CC-BY-4.0"
}
